name: run_business_card

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: basic # You can customize this based on your LaTeX packages requirements

      - name: Compile LaTeX Document
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error card.tex
          # Run additional commands if needed, e.g., bibtex, makeindex, etc.

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: card.pdf
          path: card.pdf
